# Generated by Django 2.0.2 on 2018-04-06 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signature', '0002_auto_20180406_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetail',
            new_name='UserProfile',
        ),
    ]
