# Generated by Django 2.0.2 on 2018-04-07 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0005_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='user',
        ),
        migrations.AddField(
            model_name='signature',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='email',
            field=models.CharField(default='rahulpugal.0308@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
